### ISSUE TITLE
task fails for path with whitespaces

### ISSUE THREAD

**Issue by alanwilter** [GothenburgBitFactory/taskwarrior#3585]
I'm working on Mac.

This is my `Taskfile.yml`:

```yml
version: "3"

tasks:
  build-linux:
    aliases: [build, default]
    desc: Build the project for Linux
    env:
      ARCH: amd64
    cmds:
      - docker buildx build --platform "linux/${ARCH}" --progress plain -t crystal-eye .
      - docker run -u $(id -u) -v "/tmp:/workspace" crystal-eye cp bin/crystal-eye
        /workspace/crystal-eye
      - mkdir -p bin
      - mv /tmp/crystal-eye bin/crystal-eye

  build-mac:
    desc: Build the project for macOS
    cmds:
      - shards install
      - brew install grokj2k jpeg-turbo libspng
      - crystal build --no-debug --release -o bin/crystal-eye src/cli.cr
```

My project is located at `~/Library/Mobile Documents/com~apple~CloudDocs/Projects/crystaleye` (note the whitespace)

When I issue `task build-mac`, I get:

```
task: [build-mac] crystal build --no-debug --release -o bin/crystal-eye src/cli.cr
find: /Users/alan/Library/Mobile: No such file or directory
find: Documents/com~apple~CloudDocs/Projects/crystaleye/src: No such file or directory
```
which never finishes.

If I move my project to an absolute path without whitespace it will work.
